-- 코드를 입력하세요
SELECT 
    TO_NUMBER(TO_CHAR(DATETIME, 'HH24')) HOUR
    , COUNT(*) COUNT
FROM ANIMAL_OUTS
WHERE TO_CHAR(DATETIME, 'HH24') BETWEEN 9 AND 20
GROUP BY TO_CHAR(DATETIME, 'HH24')
ORDER BY TO_CHAR(DATETIME, 'HH24')


-- SELECT *
-- FROM ANIMAL_OUTS